config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users
  # resources :discussions, only: %i[index create new]
  resources :discussions, only: %i[index show new create edit update destroy] do
    resources :posts, only: %i[create show edit update destroy], module: :discussions
  end
  root to: 'main#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  
  has_many :discussions, dependent: :nullify

  scope :sorted, -> { order(name: :asc) }

  after_create_commint -> { broadcast_prepend_to 'categories' }
  after_update_commint -> { broadcast_replace_to 'categories' }
  after_destroy_commint -> { broadcast_remove_to 'categories' }
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/discussion.rb
class Discussion < ApplicationRecord
  belongs_to :user, default: -> { Current.user }
  belongs_to :category, counter_cache: true, touch: true

  delegate :name, prefix: :category, to: :category, allow_nil: true

  has_many :posts, dependent: :destroy

  accepts_nested_attributes_for :posts

  after_create_commit -> { broadcast_prepend_to 'discussions' }
  after_update_commit -> { broadcast_replace_to 'discussions' }
  after_destroy_commit -> { broadcast_remove_to 'discussions' }

  validates :name, presence: true

  def to_param
    "#{id}-#{name.downcase.to_s[0...100]}".parameterize
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :discussion, counter_cache: true, touch: true
  belongs_to :user, default: -> { Current.user }

  has_rich_text :body

  validates :body, presence: true

  after_create_commit lambda {
    broadcast_append_to discussion, partial: 'discussions/posts/post', locals: { post: self }
  }
  after_update_commit lambda {
    broadcast_replace_to discussion, partial: 'discussions/posts/post', locals: { post: self }
  }

  after_destroy_commit -> { broadcast_remove_to discussion }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true, uniqueness: true

  has_many :discussions, dependent: :destroy
  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_current_user, if: :user_signed_in?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  def set_current_user
    Current.user = current_user
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :discussions_count)
    end
end

app/controllers/discussions/posts_controller.rb
module Discussions
  class PostsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_discussion
    before_action :set_post, only: %i[show edit update destroy]

    def show; end

    def edit; end

    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to @post.discussion, notice: 'Post updated' }
        else
          format.html { render :edit, status: :unprocessable_entity }
        end
      end
    end

    def create
      @post = @discussion.posts.new(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to discussion_path(@discussion), notice: 'Post created' }
        else
          format.turbo_stream
          format.html { render :new, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @post.destroy

      respond_to do |format|
        format.turbo_stream {} # let the callback delete the post
        format.html { redirect_to @post.discussion, notice: 'Post deleted' }
      end
    end

    private

    def set_discussion
      @discussion = Discussion.find(params[:discussion_id])
    end

    def set_post
      @post = @discussion.posts.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:body)
    end
  end
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_discussion, only: %i[show edit update destroy]

  def index
    @discussions = Discussion.all.order(updated_at: :desc)
  end

  def new
    @discussion = Discussion.new
    @discussion.posts.new
  end

  def show
    @posts = @discussion.posts.all.order(created_at: :asc)
    @new_post = @discussion.posts.new
  end

  def create
    @discussion = Discussion.new(discussion_params)
    respond_to do |format|
      if @discussion.save
        format.html { redirect_to @discussion, notice: 'Discussion created' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @discussion.update(discussion_params)
        @discussion.broadcast_replace(partial: 'discussions/header', locals: { discussion: @discussion })
        format.html { redirect_to @discussion, notice: 'Discussion updated' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @discussion.destroy!
    redirect_to discussions_path, notice: 'Discussion removed'
  end

  private

  def discussion_params
    params.require(:discussion).permit(:name, :category_id, :closed, :pinned, posts_attributes: :body)
  end

  def set_discussion
    @discussion = Discussion.find(params[:id])
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index; end
end

app/controllers/users/devise_controller.rb
class Users::DeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/categories/_category.html.erb
<div id="<%= dom_id(category) %>" class="d-flex align-items-start justify-content-between">
  <h4><%= category.name %></h4>
  <span class="badge bg-secondary rounded-pill text-light"><%= category.discussions_count if category.discussions_count&.positive? %></span>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :discussions_count %>
    <%= form.number_field :discussions_count %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Discussions count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.discussions_count %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Discussions count:</strong>
  <%= @category.discussions_count %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/discussions/_discussion.html.erb
<div id='<%= dom_id(discussion) %>', class='mb-2' >
  <h2><%= link_to discussion.name, discussion %></h2>
  Pinned: <%= discussion.pinned %> | Closed: <%= discussion.closed %><br />
  Posted in: <%= discussion.category_name %> | Posts: <%= discussion.posts_count %>
  <div>
    <%= link_to "Edit", edit_discussion_path(discussion) %>
    <%= link_to "Delete", discussion, method: :delete, data: { confirm: "Are you sure? This cannot be undone."} %>
  </div>
</div>

app/views/discussions/_form.html.erb
<%= form_with(model: discussion) do |form| %>

  <% if discussion.errors.any? %>
    <div id='error_explanation'>
      <h2><%= pluralize(discussion.errors.count, 'error') %> prevented this discussion from being saved: </h2>
      <ul>
        <% discussion.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='mb-3'>
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, placeholder: 'Hey anon...', class: 'form-control' %>
  </div>

  <div class='mb-3'>
    <%= form.label :category_id, 'Choose a category', class: 'form-label' %>
    <%= form.collection_select :category_id, Category.sorted, :id, :name, 
        { include_blank: 'Pick a category...'}, { autofocus: false, class: 'form-control' } %>
  </div>

  <div class='mb-3'>
    <%= form.label :pinned, class: 'form-label' %>
    <%= form.check_box :pinned %>
  </div>

  <div class='mb-3'>
    <%= form.label :closed, class: 'form-label' %>
    <%= form.check_box :closed %>
  </div>

  <% if discussion.new_record? %>
    <%= form.fields_for :posts do |p| %>
      <div class='mb-3'>
        <%= p.rich_text_area :body, placeholder: 'Kickoff the discussion' %>
      </div>
    <% end %>
  <% end %>

  <div class='mb-3'>
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/discussions/_header.html.erb
<%= turbo_frame_tag dom_id(discussion) do %>
  <div class="d-flex align-items-center justify-content-between">
    <div>
      <h1><%= discussion.name %></h1>
      <span class='text-muted fs-6'>
        <% if discussion.pinned %>
          <span class='badge rounded-pill bg-info'>Pinned</span>
        <% end %>
        <% if discussion.closed %>
          <span class='badge rounded-pill text-danger'>Closed</span>
        <% end %>
      </span>
    </div>
    <div>
      <%= link_to "Edit", edit_discussion_path(discussion) %>
      <%= link_to "Delete", discussion, method: :delete, data: { confirm: "Are you sure?" } %>
    </div>
  </div>
<% end %>

app/views/discussions/edit.html.erb
<h1>Edit discussion</h1>
<%= turbo_frame_tag dom_id(@discussion) do %>
  <%= render("form", discussion: @discussion) %>
  <%= link_to "Cancel", @discussion %>
<% end %>

app/views/discussions/index.html.erb
<%= turbo_stream_from 'discussions' %>
<div class='d-flex justify-content-between align-items-center'>
  <h1>Discussions</h1>
  <%= link_to "New discussion", new_discussion_path, class: 'btn btn-primary' %>
</div>

<div class='row mt-4'>
  <div class="col-3">
    <%= turbo_stream_from 'categories' %>
    <h5>Categories</h5>
    <div id="categories">
      <%= render(partial: "categories/category", collection: Category.sorted) %>
    </div>
  </div>
  <div class='col'>
    <div id='discussions'>
      <%= render @discussions %>
    </div>
  </div>
</div>

app/views/discussions/new.html.erb
<h1>New discussion</h1>

<%= render("form", discussion: @discussion) %>

app/views/discussions/posts/_form.html.erb
<%= turbo_frame_tag "#{dom_id(post)}_form", target: '_top' do %>
  <%= form_with(model: [post.discussion, post]) do |form| %>
    <% if post.errors.any? %>
      <div id='error_explanation'>
        <h2><%= pluralize(post.errors.count, 'error') %> prohibited this post from being saved:</h2>
        <ul>
          <% post.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>

    <% end %>

    <div class='mb-3'>
      <%= form.label :body, class: 'visually-hidden form-label' %>
      <%= form.rich_text_area :body, placeholder: 'Add your comment', autofocus: true %>
    </div>
     
    <div class='mb-3'>
      <%= form.submit class: 'btn btn-primary' %>
    </div>
  <% end %>
<% end %>

app/views/discussions/posts/_header.html.erb
<h4 class='card-title'> <%= post.user.username %></h4>
<h6 class='card-subtitle mb-3 text-muted border-bottom pb-3'>posted on: <%= post.created_at %></h6>

app/views/discussions/posts/_post.html.erb
<%= turbo_frame_tag dom_id(post) do %>
  <div class='card my-4'>
    <div class='card-body'>
      <%= render(partial: 'discussions/posts/header', locals: { post: post }) %>
      <%= post.body %>
    </div>

    <div class='card-footer'>
      <%= link_to 'Edit', edit_discussion_post_path(post.discussion, post), data: { turbo_frame: dom_id(post)} %>
      <%= link_to 'Delete', discussion_post_path(post.discussion, post), method: :delete %>
    </div>
  </div>
<% end %>

app/views/discussions/posts/create.turbo_stream.erb
<%= turbo_stream.replace 'new_post_form' do %>
  <%= render partial: 'discussions/posts/form', locals: { post: @post } %>
<% end %>

app/views/discussions/posts/edit.html.erb
<h1>Edit post</h1>
<%= turbo_frame_tag dom_id(@post) do %>
  <div class='card my-4'>
    <div class='card-body'>
      <%= render(partial: 'discussions/posts/header', locals: { post: @post }) %>
      <%= render('form', post: @post) %>
      <%= link_to 'Back', discussion_post_path(@post.discussion, @post) %>
    </div>
  </div>
<% end %>

app/views/discussions/posts/show.html.erb
<%= render partial: 'discussions/posts/post', locals: { post: @post } %>

app/views/discussions/show.html.erb
<%= turbo_stream_from @discussion %>
<%= render(partial: "discussions/header", locals: { discussion: @discussion}) %>
<div id='posts' class='mt-4'>
  <%= render(partial: 'discussions/posts/post', collection: @posts) %>
</div>
<hr class='my-4'>
<div id='<%= dom_id(@new_post)%>'>
  <%= render('discussions/posts/form', post: @new_post) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wirums</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbo-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
</head>

  <body>
    <%= render("shared/navigation") %>
    <div class="container mt-5">
      <%= render("shared/flash") %>   
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<h1>Main#index</h1>
<p>Find me in app/views/main/index.html.erb</p>

app/views/shared/_flash.html.erb
<% if notice %>
  <div class="alert alert-info mb-4" role="alert">
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning mb-4" role="alert">
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Hotwire Forums", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <%= link_to "Discussions", discussions_path, class: "nav-item nav-link" %>
          <%= link_to "Categories", categories_path, class: "nav-item nav-link" %>
      </ul>
      <ul class="navbar-nav mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <%= link_to Current.user.username, edit_user_registration_path, class: "nav-item nav-link" %>
          <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-item nav-link" %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, class: "nav-item nav-link" %>
          <%= link_to "Login", new_user_session_path, class: "nav-item nav-link" %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>